[package]
name = "tinker"
version = "0.1.0"
edition = "2021"

[dependencies]
wry = { version = "0.37", features = ["transparent"] }
tao = { version = "0.25", features = ["rwh_05"] }
raw-window-handle = "0.5.2"
tokio = { version = "1.35.1", features = ["full"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
anyhow = "1.0.79"
url = "2.5.0"
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
rumqttc = "0.24"
axum = "0.7"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.48", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
objc = "0.2"
