[package]
name = "tinker"
version = "0.1.0"
edition = "2021"

[features]
default = ["webview", "native-ui"]
full = ["webview", "native-ui", "v8", "javascriptcore", "spidermonkey"]

# Core features
webview = ["dep:wry", "dep:tao"]
native-ui = []

# JavaScript engines
v8 = ["dep:v8"]
javascriptcore = ["dep:javascriptcore-rs"]
spidermonkey = ["dep:mozjs"]

[dependencies]
# Core dependencies (always included)
anyhow = "1.0.79"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
raw-window-handle = "0.5.2"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"

# Optional dependencies based on features
wry = { version = "0.37", features = ["transparent"], optional = true }
tao = { version = "0.25", features = ["rwh_05"], optional = true }
v8 = { version = "0.74", optional = true }
javascriptcore-rs = { version = "0.14", optional = true }
mozjs = { version = "0.10.1", optional = true }

# Platform-specific dependencies
[target.'cfg(windows)'.dependencies]
windows = { version = "0.48", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
    "Win32_UI_Controls",
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_System_Threading",
]}

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
